import{S as y,i as d,a as h}from"./assets/vendor-DEenWwFD.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const f=document.querySelector(".img-list"),L=document.querySelector(".load-more-btn");function v(r){if(r.hits.length>0){const l=r.hits.map(s=>`<li class="img-item">
        <div class="gallery">
        <a href=${s.largeImageURL}><img class="img" src=${s.webformatURL} alt=${s.tags}/></a></div>
        <ul class="img-descr-list">
        <li class="img-descr-item"><h4 class="descr-name">Likes</h4><p class="descr-value">${s.likes}</p></li>
        <li class="img-descr-item"><h4 class="descr-name">Views</h4><p class="descr-value">${s.views}</p></li>
        <li class="img-descr-item"><h4 class="descr-name">Comments</h4><p class="descr-value">${s.comments}</p></li>
        <li class="img-descr-item"><h4 class="descr-name">Downloads</h4><p class="descr-value">${s.downloads}</p></li>
        </ul>
      </li>`).join("");f.insertAdjacentHTML("beforeend",l),new y(".gallery a",{captionDelay:250})}else L.classList.add("hiddent"),d.error({message:"Sorry, there are no images matching your search query. Please try again!"}),f.innerHTML=""}let m=0;async function g(r,l){h.defaults.baseURL="https://pixabay.com/api";try{const s=await h.get("/",{params:{key:"42078504-06c0bc861c70afe486d8727f6",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:42}});return v(s.data),m=s.data.totalHits,s.data}catch(s){d.error({message:s.message})}}const e={form:document.querySelector(".form"),list:document.querySelector(".img-list"),loader:document.querySelector(".loader-container"),loadMore:document.querySelector(".load-more-btn"),scrollUp:document.querySelector(".scroll-up-btn")};let a=1,n=1,i="",p=0;e.loader.classList.add("hidden");e.loadMore.classList.add("hidden");e.form.addEventListener("submit",w);function w(r){if(r.preventDefault(),e.loadMore.classList.add("hidden"),e.loader.classList.remove("hidden"),i=r.target.elements.search.value.trim(),i)g(i,a).finally(()=>{n=Math.ceil(m/40),e.loader.classList.add("hidden"),n>1?e.loadMore.classList.remove("hidden"):e.loadMore.classList.add("hidden")});else{d.error({message:"Sorry, searchfield can not be empty. Please, try again!"}),e.loadMore.classList.add("hidden"),e.list.innerHTML="",e.loader.classList.add("hidden");return}e.form.reset(),e.list.innerHTML=""}e.loadMore.addEventListener("click",M);function M(){e.loader.classList.remove("hidden"),e.loadMore.classList.add("hidden"),a++,g(i,a).finally(()=>{e.loader.classList.add("hidden"),e.loadMore.classList.remove("hidden"),p=document.querySelector(".img-item").getBoundingClientRect();let r=Math.floor(p.height)*2;window.scrollBy({top:r,left:0,behavior:"smooth"}),(a===n||m<40)&&(e.loadMore.classList.add("hidden"),d.info({message:"We're sorry, but you've reached the end of search results."}))})}e.scrollUp.addEventListener("click",b);function b(){window.scroll({top:0,left:0,behavior:"smooth"})}document.addEventListener("scroll",S);function S(r){console.log(window.scrollY),console.log(window.innerHeight),window.scrollY<window.innerHeight?e.scrollUp.classList.add("hidden"):e.scrollUp.classList.remove("hidden")}
//# sourceMappingURL=index.js.map
